apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
patches:
  - path: ./patches-env.yaml
    target:
      kind: Deployment
images:
  - name: rpaazuredevcr.azurecr.io/rpaazure
    newTag: a5af404081dabcab4aff4b408703f17c0b33ed97
