apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
patches:
  - path: ./patches-env.yaml
    target:
      kind: Deployment
images:
  - name: rpaazuredevcr.azurecr.io/rpaazure
    newTag: 0336888e62f58d1ac5f78cd28f21f50a83f0001a
