apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- path: ./patches-env.yaml
  target:
    kind: Deployment

images:
  - name: rpaazuredevcr.azurecr.io/rpaazure
    newTag: a5461a3f4dd6be2cb204925df0fb64499a547921
