apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd

bases:
- ../../base

patches:
- path: ./patches-env.yaml
  target:
    kind: Deployment

images:
  - name: rpaazuredevcr.azurecr.io/rpaazure
    newTag: v1
